/**
 * Tipos Comuns - Sistema de Educação Médica SOTA
 * Tipos base reutilizados em toda aplicação
 */

// Enums do Prisma
export enum UserType {
  STUDENT = 'STUDENT',
  INSTRUCTOR = 'INSTRUCTOR',
  ADMIN = 'ADMIN',
  INSTITUTION = 'INSTITUTION'
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY'
}

export enum StudentLevel {
  FIRST_YEAR = 'FIRST_YEAR',
  SECOND_YEAR = 'SECOND_YEAR',
  THIRD_YEAR = 'THIRD_YEAR',
  FOURTH_YEAR = 'FOURTH_YEAR',
  FIFTH_YEAR = 'FIFTH_YEAR',
  SIXTH_YEAR = 'SIXTH_YEAR',
  INTERNSHIP = 'INTERNSHIP',
  RESIDENCY = 'RESIDENCY',
  SPECIALIZATION = 'SPECIALIZATION'
}

export enum MedicalSpecialty {
  ANATOMIA = 'ANATOMIA',
  FISIOLOGIA = 'FISIOLOGIA',
  FARMACOLOGIA = 'FARMACOLOGIA',
  PATOLOGIA = 'PATOLOGIA',
  MICROBIOLOGIA = 'MICROBIOLOGIA',
  IMUNOLOGIA = 'IMUNOLOGIA',
  BIOQUIMICA = 'BIOQUIMICA',
  GENETICA = 'GENETICA',
  CARDIOLOGIA = 'CARDIOLOGIA',
  PNEUMOLOGIA = 'PNEUMOLOGIA',
  GASTROENTEROLOGIA = 'GASTROENTEROLOGIA',
  NEFROLOGIA = 'NEFROLOGIA',
  ENDOCRINOLOGIA = 'ENDOCRINOLOGIA',
  HEMATOLOGIA = 'HEMATOLOGIA',
  ONCOLOGIA = 'ONCOLOGIA',
  NEUROLOGIA = 'NEUROLOGIA',
  PSIQUIATRIA = 'PSIQUIATRIA',
  PEDIATRIA = 'PEDIATRIA',
  GINECOLOGIA = 'GINECOLOGIA',
  OBSTETRICIA = 'OBSTETRICIA',
  DERMATOLOGIA = 'DERMATOLOGIA',
  OFTALMOLOGIA = 'OFTALMOLOGIA',
  OTORRINOLARINGOLOGIA = 'OTORRINOLARINGOLOGIA',
  UROLOGIA = 'UROLOGIA',
  ORTOPEDIA = 'ORTOPEDIA',
  CIRURGIA_GERAL = 'CIRURGIA_GERAL',
  ANESTESIOLOGIA = 'ANESTESIOLOGIA',
  RADIOLOGIA = 'RADIOLOGIA',
  MEDICINA_ESPORTIVA = 'MEDICINA_ESPORTIVA',
  MEDICINA_TROPICAL = 'MEDICINA_TROPICAL',
  SAUDE_PUBLICA = 'SAUDE_PUBLICA',
  MEDICINA_FAMILIAR = 'MEDICINA_FAMILIAR',
  EMERGENCIA = 'EMERGENCIA',
  INTENSIVISMO = 'INTENSIVISMO'
}

export enum LearningStyle {
  VISUAL = 'VISUAL',
  AUDITORY = 'AUDITORY',
  KINESTHETIC = 'KINESTHETIC',
  READING_WRITING = 'READING_WRITING',
  MULTIMODAL = 'MULTIMODAL'
}

export enum LearningPace {
  SLOW = 'SLOW',
  NORMAL = 'NORMAL',
  FAST = 'FAST',
  ACCELERATED = 'ACCELERATED'
}

export enum ExamType {
  ENAMED = 'ENAMED',
  RESIDENCIA = 'RESIDENCIA',
  PROVA_PRATICA = 'PROVA_PRATICA',
  AVALIACAO_UNIVERSITARIA = 'AVALIACAO_UNIVERSITARIA',
  ESPECIALIZACAO = 'ESPECIALIZACAO',
  CERTIFICACAO = 'CERTIFICACAO'
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  CONTENT_ADMIN = 'CONTENT_ADMIN',
  INSTITUTION_ADMIN = 'INSTITUTION_ADMIN',
  SUPPORT_ADMIN = 'SUPPORT_ADMIN'
}

export enum InstitutionType {
  UNIVERSITY = 'UNIVERSITY',
  MEDICAL_SCHOOL = 'MEDICAL_SCHOOL',
  HOSPITAL = 'HOSPITAL',
  RESEARCH_INSTITUTE = 'RESEARCH_INSTITUTE',
  PROFESSIONAL_ASSOCIATION = 'PROFESSIONAL_ASSOCIATION',
  GOVERNMENT_AGENCY = 'GOVERNMENT_AGENCY'
}

export enum ContentType {
  TEXT = 'TEXT',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  INTERACTIVE = 'INTERACTIVE',
  SIMULATION = 'SIMULATION',
  CASE_STUDY = 'CASE_STUDY',
  QUESTION = 'QUESTION',
  ASSESSMENT = 'ASSESSMENT',
  INFOGRAPHIC = 'INFOGRAPHIC',
  DIAGRAM = 'DIAGRAM',
  ANIMATION = 'ANIMATION',
  VR_EXPERIENCE = 'VR_EXPERIENCE',
  AR_OVERLAY = 'AR_OVERLAY',
  COLLABORATION = 'COLLABORATION',
  DISCUSSION = 'DISCUSSION'
}

export enum ContentFormat {
  MARKDOWN = 'MARKDOWN',
  HTML = 'HTML',
  PDF = 'PDF',
  VIDEO_MP4 = 'VIDEO_MP4',
  AUDIO_MP3 = 'AUDIO_MP3',
  IMAGE_PNG = 'IMAGE_PNG',
  IMAGE_JPG = 'IMAGE_JPG',
  SVG = 'SVG',
  WEB_APP = 'WEB_APP',
  UNITY_BUILD = 'UNITY_BUILD',
  WEBXR = 'WEBXR',
  JSON = 'JSON',
  XML = 'XML'
}

export enum CourseLevel {
  INTRODUCTORY = 'INTRODUCTORY',
  BASIC = 'BASIC',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
  EXPERT = 'EXPERT',
  SPECIALIZED = 'SPECIALIZED'
}

export enum SessionType {
  STUDY_SESSION = 'STUDY_SESSION',
  ASSESSMENT_SESSION = 'ASSESSMENT_SESSION',
  REVIEW_SESSION = 'REVIEW_SESSION',
  COLLABORATION_SESSION = 'COLLABORATION_SESSION',
  AI_TUTORING_SESSION = 'AI_TUTORING_SESSION',
  VR_PRACTICE = 'VR_PRACTICE',
  CASE_DISCUSSION = 'CASE_DISCUSSION'
}

export enum SessionStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
  EXPIRED = 'EXPIRED'
}

export enum InteractionType {
  CLICK = 'CLICK',
  SCROLL = 'SCROLL',
  KEYBOARD = 'KEYBOARD',
  VOICE = 'VOICE',
  GESTURE = 'GESTURE',
  VR_INTERACTION = 'VR_INTERACTION',
  AR_INTERACTION = 'AR_INTERACTION'
}

export enum InsightType {
  PERFORMANCE_ANALYSIS = 'PERFORMANCE_ANALYSIS',
  LEARNING_RECOMMENDATION = 'LEARNING_RECOMMENDATION',
  DIFFICULTY_ADJUSTMENT = 'DIFFICULTY_ADJUSTMENT',
  CONTENT_SUGGESTION = 'CONTENT_SUGGESTION',
  STUDY_SCHEDULE = 'STUDY_SCHEDULE',
  MOTIVATION_FEEDBACK = 'MOTIVATION_FEEDBACK',
  ENGAGEMENT_INSIGHT = 'ENGAGEMENT_INSIGHT',
  PREDICTION = 'PREDICTION'
}

export enum AssessmentType {
  QUIZ = 'QUIZ',
  EXAM = 'EXAM',
  PRACTICAL_ASSESSMENT = 'PRACTICAL_ASSESSMENT',
  CASE_ANALYSIS = 'CASE_ANALYSIS',
  PORTFOLIO = 'PORTFOLIO',
  ORAL_EXAMINATION = 'ORAL_EXAMINATION',
  PEER_ASSESSMENT = 'PEER_ASSESSMENT',
  SELF_ASSESSMENT = 'SELF_ASSESSMENT',
  CONTINUOUS_ASSESSMENT = 'CONTINUOUS_ASSESSMENT',
  ADAPTIVE_TEST = 'ADAPTIVE_TEST'
}

export enum QuestionType {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  TRUE_FALSE = 'TRUE_FALSE',
  SHORT_ANSWER = 'SHORT_ANSWER',
  LONG_ANSWER = 'LONG_ANSWER',
  ESSAY = 'ESSAY',
  DRAG_DROP = 'DRAG_DROP',
  MATCHING = 'MATCHING',
  FILL_IN_BLANK = 'FILL_IN_BLANK',
  SCENARIO_BASED = 'SCENARIO_BASED',
  INTERACTIVE_SIMULATION = 'INTERACTIVE_SIMULATION'
}

export enum CognitiveLevel {
  REMEMBER = 'REMEMBER',
  UNDERSTAND = 'UNDERSTAND',
  APPLY = 'APPLY',
  ANALYZE = 'ANALYZE',
  EVALUATE = 'EVALUATE',
  CREATE = 'CREATE'
}

export enum AttemptStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
  EXPIRED = 'EXPIRED'
}

export enum PlanStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED'
}

export enum ActivityType {
  STUDY_CONTENT = 'STUDY_CONTENT',
  PRACTICE_QUESTIONS = 'PRACTICE_QUESTIONS',
  REVIEW_SESSION = 'REVIEW_SESSION',
  ASSESSMENT = 'ASSESSMENT',
  COLLABORATION = 'COLLABORATION',
  VR_PRACTICE = 'VR_PRACTICE',
  CASE_DISCUSSION = 'CASE_DISCUSSION',
  READING = 'READING',
  VIDEO_WATCHING = 'VIDEO_WATCHING'
}

export enum ActivityStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  CANCELLED = 'CANCELLED'
}

export enum AchievementType {
  COURSE_COMPLETION = 'COURSE_COMPLETION',
  ASSESSMENT_SCORE = 'ASSESSMENT_SCORE',
  STREAK_MILESTONE = 'STREAK_MILESTONE',
  COMPETENCY_MASTERY = 'COMPETENCY_MASTERY',
  SPEED_LEARNING = 'SPEED_LEARNING',
  COLLABORATION = 'COLLABORATION',
  STREAK_SPECIAL = 'STREAK_SPECIAL',
  RESEARCH_CONTRIBUTION = 'RESEARCH_CONTRIBUTION',
  PEER_HELPING = 'PEER_HELPING',
  SYSTEM_FEEDBACK = 'SYSTEM_FEEDBACK'
}

export enum CredentialType {
  COURSE_COMPLETION = 'COURSE_COMPLETION',
  COMPETENCY_CERTIFICATION = 'COMPETENCY_CERTIFICATION',
  SKILL_BADGE = 'SKILL_BADGE',
  ASSESSMENT_CERTIFICATE = 'ASSESSMENT_CERTIFICATE',
  MILESTONE_ACHIEVEMENT = 'MILESTONE_ACHIEVEMENT',
  PEER_RECOGNITION = 'PEER_RECOGNITION',
  INSTITUTION_CERTIFICATE = 'INSTITUTION_CERTIFICATE',
  BLOCKCHAIN_VERIFIED = 'BLOCKCHAIN_VERIFIED'
}

export enum CredentialStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
  SUSPENDED = 'SUSPENDED'
}