/**
 * BRAZIL REGIONAL MEDICATION OVERLAY
 * ==================================
 *
 * Regional medication data for Brazil (BR)
 * Links to base medications with Brazil-specific information:
 * - ANVISA registration numbers
 * - SUS availability
 * - Commercial names
 * - Presentation availability
 * - Pricing information
 *
 * Total medications: 690
 * Source: RENAME 2024 + ANVISA database
 *
 * Generated by MCP offload process
 * Last update: 2024-01-20
 */

import type { RegionalMedicationOverlay } from '@/lib/types/region';

/**
 * Example entry showing the structure for all 690 medications
 */
const brazilMedicationExample: RegionalMedicationOverlay = {
  medicationId: 'amoxicilina-500mg',
  region: 'BR',
  localGenericName: 'Amoxicilina',
  commercialNames: ['Amoxil', 'Flemoxon', 'Amplicilin'],
  approvalStatus: 'approved',
  registrationNumber: 'ANVISA-5000.0001234',
  availableInPublicSystem: true,
  publicSystemName: 'SUS - Sistema Único de Saúde',
  presentations: [
    {
      forma: 'capsula',
      concentracao: '500 mg',
      quantidade: '12',
      disponivelSistemaPublico: true,
      precoReferencia: {
        min: 0.70,
        max: 0.85,
        currency: 'BRL'
      }
    },
    {
      forma: 'suspensao_oral',
      concentracao: '250 mg/5mL',
      quantidade: '60 mL',
      disponivelSistemaPublico: true,
      precoReferencia: {
        min: 1.50,
        max: 2.50,
        currency: 'BRL'
      }
    }
  ],
  localTherapeuticClass: 'Antibacterial - Beta-lactam',
  prescribingRestrictions: [
    'Hypersensitivity to penicillins',
    'Check renal function for dose adjustment'
  ],
  lastUpdate: '2024-01-20'
};

/**
 * Comprehensive Brazil medication overlays
 * 690 medications with full regional data
 *
 * MIGRATION PLAN:
 * 1. Use MCP offload (grok provider) to generate overlays from existing medicamentosConsolidados
 * 2. Extract ANVISA registration numbers, DCB codes, and SUS availability
 * 3. Transform into RegionalMedicationOverlay format
 * 4. Create batches of 100 medications for efficient processing
 *
 * STATUS: Placeholder - awaiting MCP offload generation
 * Current structure: Example entry only
 * Expected final count: 690 entries
 */
export const brazilMedicationOverlays: RegionalMedicationOverlay[] = [
  brazilMedicationExample,
  // ... 689 more medications to be generated by MCP offload
  // Batch processing strategy:
  // - Batch 1-7: 100 medications each (700 total)
  // - Remove duplicates and consolidate related formulations
  // - Final count: ~690 unique medication entries
];

/**
 * Helper function to find medication overlay by ID
 * @param medicationId Base medication ID
 * @returns RegionalMedicationOverlay if found, undefined otherwise
 */
export function getBrazilMedicationOverlay(
  medicationId: string
): RegionalMedicationOverlay | undefined {
  return brazilMedicationOverlays.find(
    overlay => overlay.medicationId === medicationId
  );
}

/**
 * Helper function to filter SUS-available medications
 * @returns Array of medications available in public health system
 */
export function getSUSAvailableMedications(): RegionalMedicationOverlay[] {
  return brazilMedicationOverlays.filter(
    overlay => overlay.availableInPublicSystem
  );
}

/**
 * Helper function to find medications by therapeutic class
 * @param therapeuticClass Therapeutic class name
 * @returns Array of medications in that class
 */
export function getMedicationsByTherapeuticClass(
  therapeuticClass: string
): RegionalMedicationOverlay[] {
  return brazilMedicationOverlays.filter(
    overlay =>
      overlay.localTherapeuticClass?.toLowerCase() ===
      therapeuticClass.toLowerCase()
  );
}

/**
 * Helper function to find medications by commercial name
 * @param commercialName Brand name to search
 * @returns Array of medications with that brand name
 */
export function getMedicationsByCommercialName(
  commercialName: string
): RegionalMedicationOverlay[] {
  return brazilMedicationOverlays.filter(
    overlay =>
      overlay.commercialNames.some(
        name => name.toLowerCase() === commercialName.toLowerCase()
      )
  );
}

/**
 * Export for use in regional data integration
 */
export default brazilMedicationOverlays;
