/**
 * ANALGESICOS NOVOS - DARWIN-MFC EXPANSAO 1000
 * =============================================
 * Analgesicos avancados incluindo opioides atipicos, antagonistas opioides,
 * COX-2 seletivos, analgesicos topicos e agentes especiais
 *
 * Referencias:
 * - PharmGKB Clinical Pharmacogenomics Guidelines
 * - CDC Guideline for Prescribing Opioids (2022)
 * - WHO Guidelines on Pain Management
 * - NICE Pain Management Guidelines
 * - FDA/EMA Prescribing Information
 * - Cochrane Reviews on Chronic Pain
 * - ASRA Pain Medicine Guidelines
 */

import { Medicamento } from '@/lib/types/medicamento';

export const analgesicosNovos: Partial<Medicamento>[] = [
  // =============================================================================
  // OPIOIDES ATIPICOS E AGONISTAS PARCIAIS
  // =============================================================================
  {
    id: 'tapentadol',
    nomeGenerico: 'Tapentadol',
    nomesComerciais: ['Nucynta', 'Palexia'],
    atcCode: 'N02AX06',
    rxNormCui: '787390',
    drugBankId: 'DB06204',
    snomedCT: '441743008',
    casNumber: '175591-23-8',
    classeTerapeutica: 'analgesico',
    subclasse: 'opioide_forte',
    rename: false,
    pharmgkb: [
      {
        gene: 'CYP2D6',
        phenotype: 'poor_metabolizer',
        implications: [
          'Tapentadol nao e significativamente metabolizado por CYP2D6',
          'Polimorfismos CYP2D6 tem impacto clinico minimo',
          'Nao requer ajuste de dose baseado em genotipo CYP2D6',
        ],
        dosageRecommendations: [
          'Dose padrao pode ser usada independente do status CYP2D6',
          'Diferente de codeina/tramadol, tapentadol nao e pro-droga dependente de CYP2D6',
        ],
      },
      {
        gene: 'OPRM1',
        variant: 'rs1799971 (A118G)',
        implications: [
          'Variante G pode reduzir resposta analgesica a opioides',
          'Portadores GG podem requerer doses mais altas',
        ],
        dosageRecommendations: [
          'Monitorar resposta analgesica',
          'Titular dose conforme necessidade',
        ],
      },
    ],
    apresentacoes: [
      { forma: 'comprimido', concentracao: '50mg', disponivelSUS: false },
      { forma: 'comprimido', concentracao: '75mg', disponivelSUS: false },
      { forma: 'comprimido', concentracao: '100mg', disponivelSUS: false },
      { forma: 'comprimido_liberacao_prolongada', concentracao: '50mg', disponivelSUS: false },
      { forma: 'comprimido_liberacao_prolongada', concentracao: '100mg', disponivelSUS: false },
      { forma: 'comprimido_liberacao_prolongada', concentracao: '150mg', disponivelSUS: false },
      { forma: 'comprimido_liberacao_prolongada', concentracao: '200mg', disponivelSUS: false },
      { forma: 'comprimido_liberacao_prolongada', concentracao: '250mg', disponivelSUS: false },
    ],
    indicacoes: [
      'Dor aguda moderada a grave (liberacao imediata)',
      'Dor cronica grave requerendo opioides continuos (liberacao prolongada)',
      'Dor neuropatica diabetica',
      'Dor lombar cronica',
      'Dor pos-operatoria',
    ],
    mecanismoAcao: 'Mecanismo dual MOR-NRI (mu-opioid receptor agonist e norepinephrine reuptake inhibitor). Agonista opioide mu com aproximadamente 18x menor afinidade que morfina, combinado com inibicao da recaptacao de noradrenalina que contribui para analgesia especialmente em dor neuropatica. Este mecanismo sinergico permite analgesia efetiva com menor carga opioide, potencialmente reduzindo efeitos adversos tipicos de opioides puros.',
    posologias: [
      {
        indicacao: 'Dor aguda moderada a grave',
        adultos: {
          dose: '50-100mg',
          frequencia: 'A cada 4-6 horas',
          doseMaxima: '700mg no primeiro dia, depois 600mg/dia',
          observacoes: 'Liberacao imediata. Segunda dose pode ser dada 1h apos a primeira se necessario.',
        },
      },
      {
        indicacao: 'Dor cronica grave',
        adultos: {
          dose: '50mg 2x/dia inicialmente, titular a cada 3 dias',
          frequencia: '12/12 horas',
          doseMaxima: '500mg/dia',
          observacoes: 'Liberacao prolongada. Nao esmagar, partir ou mastigar.',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade ao tapentadol',
      'Depressao respiratoria significativa',
      'Asma bronquica aguda ou grave',
      'Ileo paralitico',
      'Uso de IMAO nos ultimos 14 dias',
      'Intoxicacao aguda por alcool, hipnoticos, analgesicos ou psicofarmacos',
    ],
    precaucoes: [
      'Risco de abuso e dependencia - classificado como Schedule II nos EUA',
      'Depressao respiratoria - maior risco com inicio ou aumento de dose',
      'Sindrome serotoninergica - uso concomitante com serotoninergicos',
      'Insuficiencia suprarrenal - pode ocorrer com uso prolongado de opioides',
      'Hipotensao grave em hipovolemicos',
      'Convulsoes - em epilepticos ou risco aumentado',
      'Disfuncao hepatica - evitar em insuficiencia grave',
      'Prolongamento de QT - relatos em superdosagem',
    ],
    efeitosAdversos: {
      comuns: [
        'Nausea (30%)',
        'Vomitos (18%)',
        'Tontura (24%)',
        'Sonolencia (15%)',
        'Constipacao (8%)',
        'Cefaleia (15%)',
        'Fadiga',
        'Boca seca',
      ],
      graves: [
        'Depressao respiratoria',
        'Sindrome serotoninergica',
        'Convulsoes',
        'Prolongamento QT (superdosagem)',
        'Dependencia e abstinencia',
        'Angioedema (raro)',
      ],
    },
    interacoes: [
      {
        medicamento: 'IMAO (fenelzina, tranilcipromina, linezolida)',
        gravidade: 'contraindicada',
        efeito: 'Risco de sindrome serotoninergica grave, crise hipertensiva, excitacao do SNC',
        mecanismo: 'Inibicao da recaptacao de noradrenalina pelo tapentadol potenciada pelos IMAO',
        conduta: 'Contraindicado. Aguardar 14 dias apos descontinuar IMAO antes de iniciar tapentadol',
      },
      {
        medicamento: 'ISRS/IRSN (sertralina, venlafaxina)',
        gravidade: 'grave',
        efeito: 'Risco de sindrome serotoninergica',
        mecanismo: 'Sinergismo de acao sobre serotonina e noradrenalina',
        conduta: 'Evitar combinacao. Se necessario, monitorar rigorosamente',
      },
      {
        medicamento: 'Benzodiazepinicos e outros depressores do SNC',
        gravidade: 'grave',
        efeito: 'Potencializacao da depressao do SNC, risco de depressao respiratoria fatal',
        mecanismo: 'Efeito aditivo depressor sobre SNC',
        conduta: 'Evitar. Se necessario, usar menores doses de ambos',
      },
      {
        medicamento: 'Diureticos',
        gravidade: 'moderada',
        efeito: 'Hipotensao',
        mecanismo: 'Efeito aditivo hipotensor',
        conduta: 'Monitorar pressao arterial',
      },
    ],
    ajusteDoseRenal: [
      { tfg: '>30', ajuste: 'Sem ajuste necessario' },
      { tfg: '15-30', ajuste: 'Nao recomendado - dados insuficientes' },
      { tfg: '<15', ajuste: 'Nao recomendado' },
    ],
    gestacao: 'C',
    amamentacao: {
      compativel: false,
      observacao: 'Excretado no leite materno. Risco de depressao respiratoria no lactente. Contraindicado durante amamentacao.',
    },
    monitorizacao: [
      'Nivel de dor (escalas validadas)',
      'Sinais de depressao respiratoria',
      'Estado mental e sedacao',
      'Funcao intestinal (constipacao)',
      'Sinais de abuso ou dependencia (PDMP)',
      'Pressao arterial',
    ],
    orientacoesPaciente: [
      'Nao consumir alcool durante o tratamento',
      'Nao dirigir ou operar maquinas pesadas',
      'Comprimidos de liberacao prolongada: engolir inteiros, nao esmagar',
      'Relatar sintomas de tontura, confusao ou dificuldade respiratoria',
      'Nao interromper abruptamente - risco de abstinencia',
      'Guardar em local seguro - potencial de abuso',
    ],
    consideracoesEspeciais: {
      idosos: 'Iniciar com doses menores. Maior sensibilidade a efeitos adversos. Risco de quedas.',
      hepatopatas: 'Insuficiencia leve: iniciar 50mg a cada 8h. Moderada: iniciar 50mg a cada 8h com cautela. Grave: evitar uso.',
      pediatrico: 'Seguranca e eficacia nao estabelecidas em <18 anos',
    },
    doencasRelacionadas: ['dor-cronica', 'dor-neuropatica', 'neuropatia-diabetica', 'lombalgia-cronica'],
    calculadoras: ['conversao-opioides'],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['tapentadol', 'MOR-NRI', 'opioide-atipico', 'dor-neuropatica', 'Nucynta', 'Palexia'],
  },

  {
    id: 'buprenorfina',
    nomeGenerico: 'Buprenorfina',
    nomesComerciais: ['Subutex', 'Suboxone', 'Temgesic', 'Transtec', 'Belbuca', 'Butrans'],
    atcCode: 'N02AE01',
    rxNormCui: '1819',
    drugBankId: 'DB00921',
    snomedCT: '387173000',
    casNumber: '52485-79-7',
    classeTerapeutica: 'analgesico',
    subclasse: 'agonista_parcial_opioide',
    rename: false,
    pharmgkb: [
      {
        gene: 'CYP3A4',
        phenotype: 'poor_metabolizer',
        implications: [
          'Buprenorfina e metabolizada primariamente por CYP3A4',
          'Inibidores de CYP3A4 podem aumentar niveis de buprenorfina',
          'Indutores de CYP3A4 podem reduzir eficacia',
        ],
        dosageRecommendations: [
          'Monitorar ao iniciar ou descontinuar inibidores/indutores CYP3A4',
          'Pode requerer ajuste de dose',
        ],
      },
      {
        gene: 'OPRM1',
        variant: 'rs1799971 (A118G)',
        implications: [
          'Variante G associada a menor resposta analgesica',
          'Pode afetar eficacia no tratamento de dependencia',
        ],
        dosageRecommendations: [
          'Considerar titulacao individualizada',
          'Monitorar resposta clinica',
        ],
      },
      {
        gene: 'ABCB1',
        variant: 'rs1045642 (C3435T)',
        implications: [
          'Variantes podem afetar distribuicao para SNC',
          'Polimorfismos podem influenciar dose de manutencao no tratamento de dependencia',
        ],
        dosageRecommendations: [
          'Titular conforme resposta clinica',
        ],
      },
    ],
    apresentacoes: [
      { forma: 'comprimido', concentracao: '0,2mg (sublingual)', disponivelSUS: false },
      { forma: 'comprimido', concentracao: '2mg (sublingual)', disponivelSUS: false },
      { forma: 'comprimido', concentracao: '8mg (sublingual)', disponivelSUS: false },
      { forma: 'adesivo', concentracao: '5mcg/h (7 dias)', disponivelSUS: false },
      { forma: 'adesivo', concentracao: '10mcg/h (7 dias)', disponivelSUS: false },
      { forma: 'adesivo', concentracao: '20mcg/h (7 dias)', disponivelSUS: false },
      { forma: 'injetavel', concentracao: '0,3mg/mL', disponivelSUS: false },
      { forma: 'injetavel_longa_acao', concentracao: '100mg (mensal SC)', disponivelSUS: false },
      { forma: 'injetavel_longa_acao', concentracao: '300mg (mensal SC)', disponivelSUS: false },
    ],
    indicacoes: [
      'Dor moderada a grave (formas analgesicas)',
      'Dor cronica que requer opioide continuo (adesivo transdermico)',
      'Tratamento de dependencia de opioides (formas sublinguais, injetaveis depot)',
      'Manutencao em pacientes com transtorno por uso de opioides',
      'Dor oncologica (adjuvante)',
    ],
    mecanismoAcao: 'Agonista parcial do receptor opioide mu e antagonista do receptor opioide kappa. Como agonista parcial mu, produz analgesia mas com efeito teto para depressao respiratoria, conferindo maior seguranca que agonistas completos. Alta afinidade pelo receptor mu desloca outros opioides, sendo util no tratamento de dependencia. O antagonismo kappa pode contribuir para efeitos antidepressivos e menor disforia.',
    posologias: [
      {
        indicacao: 'Dor moderada a grave (sublingual)',
        adultos: {
          dose: '0,2-0,4mg sublingual',
          frequencia: 'A cada 6-8 horas',
          doseMaxima: '1,6mg/dia',
          observacoes: 'Dissolver sob a lingua. Nao engolir.',
        },
      },
      {
        indicacao: 'Dor cronica (adesivo transdermico)',
        adultos: {
          dose: 'Iniciar 5mcg/h, aumentar a cada 72h se necessario',
          frequencia: 'Trocar a cada 7 dias',
          doseMaxima: '40mcg/h (dois adesivos 20mcg)',
          observacoes: 'Aplicar em pele integra, sem pelos. Evitar calor no local.',
        },
      },
      {
        indicacao: 'Tratamento de dependencia de opioides',
        adultos: {
          dose: 'Inducao: 2-4mg SL, aumentar ate 8-16mg/dia',
          frequencia: 'Dose unica diaria',
          doseMaxima: '24mg/dia',
          observacoes: 'Iniciar em abstinencia leve-moderada (COWS 11-12). Suboxone (com naloxona) preferido para prevenir abuso IV.',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade a buprenorfina',
      'Depressao respiratoria aguda grave',
      'Alcoolismo agudo ou delirium tremens',
      'Uso concomitante de agonistas opioides completos (pode precipitar abstinencia)',
      'Miastenia gravis grave',
    ],
    precaucoes: [
      'Hepatotoxicidade - casos de hepatite e necrose hepatica relatados',
      'Depressao respiratoria - embora menor que morfina, pode ocorrer',
      'Hipotensao e sincope',
      'Sindrome de abstinencia neonatal - se usada na gestacao',
      'Risco de abuso - embora menor que opioides puros',
      'Prolongamento QTc em doses altas',
      'Reacoes alergicas ao adesivo',
    ],
    efeitosAdversos: {
      comuns: [
        'Cefaleia (30%)',
        'Nausea (15%)',
        'Constipacao (12%)',
        'Insonia (14%)',
        'Sudorese (14%)',
        'Sindrome de abstinencia (se inducao precoce)',
        'Reacoes no local do adesivo',
      ],
      graves: [
        'Hepatotoxicidade',
        'Depressao respiratoria',
        'Prolongamento QTc',
        'Abstinencia precipitada (se agonistas presentes)',
        'Dependencia',
        'Sindrome de abstinencia neonatal',
      ],
    },
    interacoes: [
      {
        medicamento: 'Benzodiazepinicos (alprazolam, diazepam)',
        gravidade: 'grave',
        efeito: 'Depressao respiratoria, coma e morte',
        mecanismo: 'Depressao aditiva do SNC',
        conduta: 'Evitar. Se necessario, usar menores doses possiveis. Black box warning da FDA.',
      },
      {
        medicamento: 'Inibidores de CYP3A4 (cetoconazol, itraconazol, ritonavir)',
        gravidade: 'moderada',
        efeito: 'Aumento dos niveis de buprenorfina, maior toxicidade',
        mecanismo: 'Inibicao do metabolismo hepatico',
        conduta: 'Reduzir dose de buprenorfina; monitorar sedacao',
      },
      {
        medicamento: 'Indutores de CYP3A4 (rifampicina, fenitoina, carbamazepina)',
        gravidade: 'moderada',
        efeito: 'Reducao dos niveis de buprenorfina, perda de eficacia',
        mecanismo: 'Aumento do metabolismo hepatico',
        conduta: 'Pode requerer aumento da dose de buprenorfina',
      },
      {
        medicamento: 'Naltrexona',
        gravidade: 'contraindicada',
        efeito: 'Antagonismo dos efeitos da buprenorfina, precipitacao de abstinencia',
        mecanismo: 'Naltrexona e antagonista opioide',
        conduta: 'Nao usar concomitantemente. Aguardar washout.',
      },
    ],
    ajusteDoseRenal: [
      { tfg: '>30', ajuste: 'Sem ajuste necessario' },
      { tfg: '<30', ajuste: 'Usar com cautela; pode haver acumulo de metabolitos' },
    ],
    gestacao: 'C',
    amamentacao: {
      compativel: false,
      observacao: 'Excretada no leite. Para maes em tratamento de dependencia, considerar risco-beneficio - AAP considera "geralmente compativel" nesse contexto.',
    },
    monitorizacao: [
      'Funcao hepatica periodica (TGO, TGP, bilirrubinas)',
      'Sinais de depressao respiratoria',
      'ECG em pacientes de risco ou doses altas (QTc)',
      'Exames toxicologicos para adesao (tratamento de dependencia)',
      'Escala COWS para inducao e manutencao',
    ],
    orientacoesPaciente: [
      'Comprimidos sublinguais: dissolver sob a lingua (5-10min)',
      'Adesivo: aplicar em pele limpa e seca, trocar semanalmente',
      'Evitar aquecer o local do adesivo (febre, sauna, bolsa termica)',
      'Nao consumir alcool',
      'Nao usar outros opioides sem orientacao',
      'Para dependencia: aderir ao programa de tratamento',
    ],
    consideracoesEspeciais: {
      idosos: 'Iniciar com doses menores. Maior sensibilidade a depressao do SNC.',
      hepatopatas: 'Hepatotoxicidade descrita. Evitar em insuficiencia grave. Monitorar enzimas hepaticas.',
      pediatrico: 'Seguranca nao estabelecida para analgesia em <18 anos. Formulacoes para dependencia: >16 anos.',
    },
    doencasRelacionadas: ['dor-cronica', 'dependencia-opioides', 'transtorno-uso-opioides', 'dor-oncologica'],
    calculadoras: ['conversao-opioides'],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['buprenorfina', 'agonista-parcial', 'MAT', 'tratamento-dependencia', 'Suboxone', 'Transtec', 'adesivo'],
  },

  // =============================================================================
  // ANTAGONISTAS OPIOIDES
  // =============================================================================
  {
    id: 'naloxona',
    nomeGenerico: 'Naloxona',
    nomesComerciais: ['Narcan', 'Evzio'],
    atcCode: 'V03AB15',
    rxNormCui: '7242',
    drugBankId: 'DB01183',
    snomedCT: '372890007',
    casNumber: '465-65-6',
    classeTerapeutica: 'tratamento_dependencia',
    subclasse: 'antagonista_opioide',
    rename: true,
    apresentacoes: [
      { forma: 'injetavel', concentracao: '0,4mg/mL (ampola 1mL)', disponivelSUS: true },
      { forma: 'spray_nasal', concentracao: '4mg/dose (spray nasal)', disponivelSUS: false },
      { forma: 'spray_nasal', concentracao: '8mg/dose (spray nasal alta dose)', disponivelSUS: false },
      { forma: 'injetavel', concentracao: '2mg/2mL (autoinjector)', disponivelSUS: false },
    ],
    indicacoes: [
      'Reversao de overdose de opioides (intoxicacao aguda)',
      'Reversao de depressao respiratoria induzida por opioides',
      'Diagnostico de dependencia de opioides (teste de naloxona)',
      'Reversao de depressao neonatal por opioides maternos',
      'Componente de formulacoes anti-abuso (Suboxone, Targin)',
    ],
    mecanismoAcao: 'Antagonista competitivo puro dos receptores opioides mu, kappa e delta, com maior afinidade pelo receptor mu. Desloca opioides agonistas dos receptores, revertendo rapidamente seus efeitos incluindo depressao respiratoria, sedacao e analgesia. Inicio de acao em 2-5 minutos (IV) ou 5-10 minutos (nasal). Duracao curta (30-90min), podendo requerer doses repetidas para opioides de longa acao.',
    posologias: [
      {
        indicacao: 'Overdose de opioide (adulto)',
        adultos: {
          dose: '0,4-2mg IV/IM/SC',
          frequencia: 'Repetir a cada 2-3 minutos se necessario',
          doseMaxima: '10mg (se nao responder, reconsiderar diagnostico)',
          observacoes: 'Titular para reverter depressao respiratoria sem induzir abstinencia completa. Via IV preferida se acesso disponivel.',
        },
      },
      {
        indicacao: 'Overdose de opioide (spray nasal)',
        adultos: {
          dose: '4mg em uma narina',
          frequencia: 'Repetir apos 2-3 minutos em narina alternada se necessario',
          observacoes: 'Chamar emergencia mesmo se paciente responder. Observar por re-sedacao.',
        },
      },
      {
        indicacao: 'Reversao pos-anestesica',
        adultos: {
          dose: '0,1-0,2mg IV',
          frequencia: 'A cada 2-3 minutos',
          observacoes: 'Titulacao cuidadosa para manter analgesia',
        },
      },
      {
        indicacao: 'Depressao respiratoria neonatal',
        pediatrico: {
          dose: '0,01mg/kg IV/IM',
          frequencia: 'Repetir a cada 2-3 minutos',
          observacoes: 'Via umbilical preferida. Evitar em neonatos de maes dependentes de opioides (risco de convulsoes).',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade a naloxona',
    ],
    precaucoes: [
      'Precipitacao de abstinencia aguda em dependentes - pode ser grave com vomitos, aspiracao',
      'Arritmias cardiacas - taquicardia, fibrilacao ventricular em pos-operatorio',
      'Edema pulmonar - casos relatados apos reversao de overdose',
      'Duracao curta - resedar se opioide de longa acao (fentanil, metadona)',
      'Neonatos de maes dependentes - risco de convulsoes',
      'Doenca cardiovascular - estresse cardiovascular da abstinencia',
    ],
    efeitosAdversos: {
      comuns: [
        'Sindrome de abstinencia (dependentes): nausea, vomitos, diarreia, sudorese, taquicardia, agitacao, dor muscular',
        'Taquicardia',
        'Hipertensao',
        'Tremores',
        'Dor no local da injecao',
      ],
      graves: [
        'Edema pulmonar',
        'Arritmias cardiacas (fibrilacao ventricular)',
        'Convulsoes (neonatos de maes dependentes)',
        'Parada cardiaca (raro)',
        'Hipertensao grave',
      ],
    },
    interacoes: [
      {
        medicamento: 'Opioides (morfina, fentanil, heroina)',
        gravidade: 'grave',
        efeito: 'Reversao dos efeitos opioides, precipitacao de abstinencia',
        mecanismo: 'Antagonismo competitivo em receptores opioides',
        conduta: 'Efeito terapeutico desejado. Titular para reverter depressao respiratoria sem abstinencia completa.',
      },
      {
        medicamento: 'Clonidina',
        gravidade: 'moderada',
        efeito: 'Pode reverter parcialmente hipotensao e bradicardia da clonidina',
        mecanismo: 'Mecanismo nao completamente elucidado',
        conduta: 'Considerar em intoxicacao por clonidina',
      },
    ],
    gestacao: 'B',
    amamentacao: {
      compativel: true,
      observacao: 'Uso agudo na reversao de overdose e compativel. Pouco absorvido oralmente pelo lactente.',
    },
    monitorizacao: [
      'Frequencia e padrao respiratorio',
      'Saturacao de oxigenio',
      'Nivel de consciencia',
      'Sinais vitais (PA, FC)',
      'Re-sedacao (opioides de longa acao)',
    ],
    orientacoesPaciente: [
      'Kits de naloxona nasal devem ser prescritos para usuarios de opioides e seus familiares',
      'Treinar familiares no uso do spray nasal',
      'SEMPRE chamar emergencia apos administrar naloxona',
      'Permanecer com a vitima - pode precisar de doses adicionais',
      'Posicionar em recuperacao (lateral) para evitar aspiracao',
    ],
    consideracoesEspeciais: {
      idosos: 'Usar com cautela em cardiopatas. Maior risco de eventos cardiovasculares.',
      pediatrico: 'Dose: 0,1mg/kg (max 2mg). Cuidado em neonatos de maes dependentes.',
    },
    doencasRelacionadas: ['overdose-opioides', 'intoxicacao-aguda', 'depressao-respiratoria'],
    calculadoras: [],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['naloxona', 'Narcan', 'antagonista-opioide', 'overdose', 'reversao', 'harm-reduction'],
  },

  {
    id: 'naltrexona',
    nomeGenerico: 'Naltrexona',
    nomesComerciais: ['Revia', 'Vivitrol'],
    atcCode: 'N07BB04',
    rxNormCui: '7243',
    drugBankId: 'DB00704',
    snomedCT: '373546002',
    casNumber: '16590-41-3',
    classeTerapeutica: 'tratamento_dependencia',
    subclasse: 'antagonista_opioide',
    rename: false,
    pharmgkb: [
      {
        gene: 'OPRM1',
        variant: 'rs1799971 (A118G)',
        implications: [
          'Portadores do alelo G podem ter melhor resposta no tratamento de alcoolismo',
          'Variante Asp40 associada a maior reducao de consumo de alcool com naltrexona',
        ],
        dosageRecommendations: [
          'Genotipagem OPRM1 pode predizer resposta',
          'Portadores 118G: maior beneficio esperado',
        ],
      },
    ],
    apresentacoes: [
      { forma: 'comprimido', concentracao: '50mg', disponivelSUS: false },
      { forma: 'injetavel_longa_acao', concentracao: '380mg (IM mensal)', disponivelSUS: false },
    ],
    indicacoes: [
      'Dependencia de alcool (reducao de consumo e prevencao de recaida)',
      'Dependencia de opioides (prevencao de recaida apos detoxificacao)',
      'Tratamento de baixa dose para dor cronica (off-label)',
      'Bulimia nervosa (off-label)',
    ],
    mecanismoAcao: 'Antagonista opioide puro com alta afinidade pelos receptores mu e kappa. No alcoolismo, bloqueia os efeitos recompensadores do alcool mediados pelo sistema opioide endogeno, reduzindo o "craving" e o prazer associado ao consumo. Na dependencia de opioides, bloqueia os efeitos euforicos de opioides exogenos, prevenindo recaida. Meia-vida longa (4h) com metabolito ativo (6-beta-naltrexol) de meia-vida 12h.',
    posologias: [
      {
        indicacao: 'Dependencia de alcool',
        adultos: {
          dose: '50mg/dia',
          frequencia: 'Dose unica diaria',
          observacoes: 'Pode iniciar com 25mg por 1-2 dias para melhor tolerabilidade. Usar como parte de programa de tratamento abrangente.',
        },
      },
      {
        indicacao: 'Dependencia de opioides',
        adultos: {
          dose: '50mg/dia ou 380mg IM mensal',
          frequencia: 'Diario (oral) ou mensal (injetavel)',
          observacoes: 'Iniciar apenas apos detoxificacao completa (7-10 dias sem opioides de curta acao, 10-14 dias sem metadona).',
        },
      },
      {
        indicacao: 'Naltrexona em baixa dose (LDN) - dor cronica',
        adultos: {
          dose: '1,5-4,5mg/dia',
          frequencia: 'Ao deitar',
          observacoes: 'Uso off-label. Evidencias limitadas. Formula manipulada.',
        },
      },
    ],
    contraindicacoes: [
      'Uso atual de opioides ou abstinencia nao completada (risco de abstinencia precipitada)',
      'Dependencia ativa de opioides',
      'Teste de provocacao com naloxona positivo',
      'Hepatite aguda ou insuficiencia hepatica',
      'Hipersensibilidade',
    ],
    precaucoes: [
      'Hepatotoxicidade - elevacao de transaminases dose-dependente',
      'Precipitacao de abstinencia se opioides presentes',
      'Bloqueio da analgesia opioide - pacientes nao responderao a opioides em emergencias',
      'Ideacao suicida - monitorar em dependentes',
      'Reacoes no local da injecao (forma IM)',
      'Trombocitopenia (rara)',
    ],
    efeitosAdversos: {
      comuns: [
        'Nausea (10%)',
        'Cefaleia (7%)',
        'Tontura (4%)',
        'Ansiedade',
        'Fadiga',
        'Insonia',
        'Dor abdominal',
      ],
      graves: [
        'Hepatotoxicidade (elevacao de transaminases)',
        'Sindrome de abstinencia precipitada',
        'Depressao e ideacao suicida',
        'Pneumonia eosinofilica (injetavel)',
        'Reacoes alergicas graves',
      ],
    },
    interacoes: [
      {
        medicamento: 'Opioides (morfina, codeina, tramadol, fentanil)',
        gravidade: 'contraindicada',
        efeito: 'Precipitacao de abstinencia aguda ou bloqueio de efeito analgesico',
        mecanismo: 'Antagonismo competitivo de receptores opioides',
        conduta: 'Evitar. Em emergencias, usar analgesicos nao-opioides ou doses muito altas de opioides sob monitoramento intensivo.',
      },
      {
        medicamento: 'Dissulfiram',
        gravidade: 'moderada',
        efeito: 'Potencial hepatotoxicidade aditiva',
        mecanismo: 'Ambos podem causar elevacao de enzimas hepaticas',
        conduta: 'Monitorar funcao hepatica rigorosamente',
      },
      {
        medicamento: 'Tioridazina',
        gravidade: 'moderada',
        efeito: 'Letargia e sonolencia aumentadas',
        mecanismo: 'Mecanismo nao elucidado',
        conduta: 'Monitorar sedacao',
      },
    ],
    ajusteDoseRenal: [
      { tfg: '>30', ajuste: 'Sem ajuste necessario' },
      { tfg: '<30', ajuste: 'Usar com cautela - acumulo de metabolitos' },
    ],
    gestacao: 'C',
    amamentacao: {
      compativel: false,
      observacao: 'Excretada no leite. Evitar uso durante amamentacao.',
    },
    monitorizacao: [
      'Funcao hepatica (TGO, TGP) baseline e periodica',
      'Exames toxicologicos para confirmar abstinencia antes de iniciar',
      'Avaliacao de humor e ideacao suicida',
      'Adesao ao tratamento',
      'Consumo de alcool (escalas, biomarcadores)',
    ],
    orientacoesPaciente: [
      'Nao usar opioides durante tratamento - serao ineficazes e podem causar overdose se tentar superar o bloqueio',
      'Portar cartao de alerta medico informando uso de naltrexona',
      'Relatar sintomas de hepatite (ictericia, urina escura)',
      'Parte de tratamento abrangente - associar a psicoterapia',
      'Injetavel: comparecer mensalmente para aplicacao',
    ],
    consideracoesEspeciais: {
      idosos: 'Usar com cautela. Monitorar funcao hepatica.',
      hepatopatas: 'Contraindicado em hepatite aguda ou ALT/AST >3x limite superior. Monitorar rigorosamente.',
      pediatrico: 'Seguranca nao estabelecida em <18 anos',
    },
    doencasRelacionadas: ['alcoolismo', 'dependencia-opioides', 'transtorno-uso-alcool'],
    calculadoras: [],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['naltrexona', 'Revia', 'Vivitrol', 'antagonista-opioide', 'alcoolismo', 'MAT'],
  },

  // =============================================================================
  // INIBIDORES SELETIVOS DE COX-2 (COXIBES)
  // =============================================================================
  {
    id: 'celecoxibe',
    nomeGenerico: 'Celecoxibe',
    nomesComerciais: ['Celebra', 'Celebrex'],
    atcCode: 'M01AH01',
    rxNormCui: '140587',
    drugBankId: 'DB00482',
    snomedCT: '116081000',
    casNumber: '169590-42-5',
    classeTerapeutica: 'anti_inflamatorio',
    subclasse: 'seletivo_cox2',
    rename: false,
    pharmgkb: [
      {
        gene: 'CYP2C9',
        phenotype: 'poor_metabolizer',
        implications: [
          'CYP2C9 e responsavel pelo metabolismo do celecoxibe',
          'Metabolizadores lentos (*2/*2, *2/*3, *3/*3) tem exposicao aumentada',
          'AUC pode aumentar 3-7x em poor metabolizers',
        ],
        dosageRecommendations: [
          'CYP2C9 *1/*1: dose padrao',
          'CYP2C9 *1/*3 ou *1/*2: iniciar com metade da dose recomendada',
          'CYP2C9 *2/*2, *3/*3, *2/*3: iniciar com 25% da dose; considerar alternativa',
        ],
      },
    ],
    apresentacoes: [
      { forma: 'capsula', concentracao: '100mg', disponivelSUS: false },
      { forma: 'capsula', concentracao: '200mg', disponivelSUS: false },
    ],
    indicacoes: [
      'Osteoartrite',
      'Artrite reumatoide',
      'Espondilite anquilosante',
      'Dismenorreia primaria',
      'Dor aguda',
      'Polipose adenomatosa familiar (reducao de polipos)',
    ],
    mecanismoAcao: 'Inibidor seletivo da ciclooxigenase-2 (COX-2). A COX-2 e induzida em processos inflamatorios, enquanto a COX-1 e constitutiva e protetora da mucosa gastrica. A seletividade COX-2 proporciona acao anti-inflamatoria e analgesica com menor toxicidade gastrointestinal comparada a AINEs nao-seletivos. Entretanto, a inibicao seletiva de COX-2 pode desequilibrar a razao prostaciclina/tromboxano, aumentando risco cardiovascular.',
    posologias: [
      {
        indicacao: 'Osteoartrite',
        adultos: {
          dose: '200mg/dia',
          frequencia: 'Dose unica ou dividida 12/12h',
          doseMaxima: '200mg/dia',
        },
      },
      {
        indicacao: 'Artrite reumatoide',
        adultos: {
          dose: '100-200mg 2x/dia',
          frequencia: '12/12 horas',
          doseMaxima: '400mg/dia',
        },
      },
      {
        indicacao: 'Espondilite anquilosante',
        adultos: {
          dose: '200mg/dia',
          frequencia: 'Dose unica ou dividida',
          doseMaxima: '400mg/dia se resposta insuficiente',
        },
      },
      {
        indicacao: 'Dor aguda / Dismenorreia',
        adultos: {
          dose: '400mg inicial, depois 200mg se necessario',
          frequencia: '12/12h apos dose inicial',
          doseMaxima: '600mg no primeiro dia, depois 400mg/dia',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade a celecoxibe ou sulfonamidas',
      'Historia de asma, urticaria ou reacoes alergicas a AAS ou AINEs',
      'Doenca arterial coronariana estabelecida',
      'Doenca cerebrovascular (AVC/AIT previos)',
      'Doenca arterial periferica',
      'Insuficiencia cardiaca NYHA II-IV',
      'Cirurgia de revascularizacao miocardica (perioperatorio)',
      'Gestacao (3o trimestre)',
      'Insuficiencia hepatica grave',
    ],
    precaucoes: [
      'Risco cardiovascular aumentado - usar menor dose pelo menor tempo',
      'Risco de eventos GI embora menor que AINEs nao-seletivos',
      'Hipertensao - pode elevar PA',
      'Retencao hidrica e edema',
      'Funcao renal - pode deteriorar',
      'Idosos - maior risco de todos os efeitos adversos',
      'Alergia a sulfonamidas - potencial reacao cruzada',
    ],
    efeitosAdversos: {
      comuns: [
        'Dispepsia (8%)',
        'Diarreia (6%)',
        'Dor abdominal (4%)',
        'Nausea',
        'Cefaleia',
        'Edema periferico (2%)',
        'Infeccao respiratoria superior',
      ],
      graves: [
        'Eventos cardiovasculares (IAM, AVC)',
        'Ulceracao e sangramento GI',
        'Insuficiencia renal aguda',
        'Reacoes cutaneas graves (Stevens-Johnson, NET)',
        'Hepatotoxicidade',
        'Reacoes anafilacticas',
      ],
    },
    interacoes: [
      {
        medicamento: 'Varfarina',
        gravidade: 'grave',
        efeito: 'Aumento do INR e risco de sangramento',
        mecanismo: 'Inibicao de CYP2C9',
        conduta: 'Monitorar INR rigorosamente ao iniciar, alterar ou descontinuar',
      },
      {
        medicamento: 'IECA/BRA',
        gravidade: 'moderada',
        efeito: 'Reducao do efeito anti-hipertensivo; risco de IRA',
        mecanismo: 'Inibicao de prostaglandinas renais',
        conduta: 'Monitorar PA e funcao renal',
      },
      {
        medicamento: 'Diureticos',
        gravidade: 'moderada',
        efeito: 'Reducao do efeito diuretico; risco de IRA',
        conduta: 'Monitorar funcao renal e resposta diuretica',
      },
      {
        medicamento: 'Litio',
        gravidade: 'moderada',
        efeito: 'Elevacao dos niveis de litio',
        mecanismo: 'Reducao da excrecao renal de litio',
        conduta: 'Monitorar litemia',
      },
      {
        medicamento: 'Fluconazol',
        gravidade: 'moderada',
        efeito: 'Aumento dos niveis de celecoxibe',
        mecanismo: 'Inibicao de CYP2C9',
        conduta: 'Reduzir dose de celecoxibe pela metade',
      },
    ],
    ajusteDoseRenal: [
      { tfg: '>30', ajuste: 'Usar com cautela' },
      { tfg: '<30', ajuste: 'Evitar uso' },
    ],
    gestacao: 'C',
    amamentacao: {
      compativel: false,
      observacao: 'Excretado no leite. Evitar; preferir alternativas.',
    },
    monitorizacao: [
      'Pressao arterial',
      'Funcao renal (creatinina, TFG)',
      'Hemograma (se uso prolongado)',
      'Sinais e sintomas GI',
      'Edema e ganho de peso',
    ],
    orientacoesPaciente: [
      'Usar a menor dose eficaz pelo menor tempo',
      'Relatar dor toracica, falta de ar, fraqueza, fala arrastada',
      'Relatar fezes escuras, vomitos com sangue',
      'Evitar outros AINEs concomitantes',
      'Informar medico sobre doencas cardiacas',
    ],
    consideracoesEspeciais: {
      idosos: 'Maior risco cardiovascular, GI e renal. Iniciar com doses menores.',
      hepatopatas: 'Moderada: reduzir dose pela metade. Grave: evitar.',
      pediatrico: 'Aprovado para artrite juvenil em >=2 anos. Dose baseada em peso.',
    },
    doencasRelacionadas: ['osteoartrite', 'artrite-reumatoide', 'espondilite-anquilosante', 'dor-aguda'],
    calculadoras: ['ckdepi'],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['celecoxibe', 'Celebra', 'COX-2', 'coxibe', 'anti-inflamatorio', 'artrite'],
  },

  {
    id: 'etoricoxibe',
    nomeGenerico: 'Etoricoxibe',
    nomesComerciais: ['Arcoxia'],
    atcCode: 'M01AH05',
    rxNormCui: '328164',
    drugBankId: 'DB01628',
    snomedCT: '407317001',
    casNumber: '202409-33-4',
    classeTerapeutica: 'anti_inflamatorio',
    subclasse: 'seletivo_cox2',
    rename: false,
    apresentacoes: [
      { forma: 'comprimido', concentracao: '30mg', disponivelSUS: false },
      { forma: 'comprimido', concentracao: '60mg', disponivelSUS: false },
      { forma: 'comprimido', concentracao: '90mg', disponivelSUS: false },
      { forma: 'comprimido', concentracao: '120mg', disponivelSUS: false },
    ],
    indicacoes: [
      'Osteoartrite',
      'Artrite reumatoide',
      'Espondilite anquilosante',
      'Gota aguda',
      'Dor aguda pos-operatoria (cirurgia dental)',
      'Dismenorreia primaria',
    ],
    mecanismoAcao: 'Inibidor altamente seletivo da COX-2, com seletividade COX-2/COX-1 maior que celecoxibe. Proporciona potente acao anti-inflamatoria e analgesica. A alta seletividade confere excelente perfil GI, mas mantem o risco cardiovascular inerente aos coxibes. Meia-vida longa (~22h) permite dose unica diaria.',
    posologias: [
      {
        indicacao: 'Osteoartrite',
        adultos: {
          dose: '30mg',
          frequencia: 'Uma vez ao dia',
          doseMaxima: '60mg/dia se resposta insuficiente',
        },
      },
      {
        indicacao: 'Artrite reumatoide',
        adultos: {
          dose: '60mg',
          frequencia: 'Uma vez ao dia',
          doseMaxima: '90mg/dia',
        },
      },
      {
        indicacao: 'Espondilite anquilosante',
        adultos: {
          dose: '60mg',
          frequencia: 'Uma vez ao dia',
          doseMaxima: '90mg/dia',
        },
      },
      {
        indicacao: 'Gota aguda',
        adultos: {
          dose: '120mg',
          frequencia: 'Uma vez ao dia',
          doseMaxima: '120mg/dia por maximo 8 dias',
        },
      },
      {
        indicacao: 'Dor aguda pos-operatoria dental',
        adultos: {
          dose: '90mg',
          frequencia: 'Uma vez ao dia',
          doseMaxima: '90mg/dia por maximo 3 dias',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade ao etoricoxibe',
      'Ulcera peptica ativa ou sangramento GI',
      'Doenca inflamatoria intestinal',
      'Insuficiencia cardiaca congestiva (NYHA II-IV)',
      'Hipertensao nao controlada (>140/90 mmHg)',
      'Doenca arterial coronariana, cerebrovascular ou periferica estabelecida',
      'Gestacao e lactacao',
      'Insuficiencia hepatica ou renal graves',
    ],
    precaucoes: [
      'Risco cardiovascular - mesmo nivel de alerta que outros coxibes',
      'Monitorar pressao arterial - mais comum que outros AINEs',
      'Retencao de sodio e edema',
      'Funcao renal - monitorar em risco',
      'Nao aprovado pela FDA nos EUA devido a preocupacoes CV',
    ],
    efeitosAdversos: {
      comuns: [
        'Hipertensao (5-8%)',
        'Edema periferico (3-4%)',
        'Cefaleia (4%)',
        'Tontura',
        'Dispepsia',
        'Nausea',
      ],
      graves: [
        'Eventos tromboembolicos (IAM, AVC)',
        'Insuficiencia cardiaca',
        'Ulceracao GI e sangramento',
        'Hepatotoxicidade',
        'Insuficiencia renal',
        'Reacoes cutaneas graves',
      ],
    },
    interacoes: [
      {
        medicamento: 'Varfarina',
        gravidade: 'grave',
        efeito: 'Aumento do INR (5-10%) e risco de sangramento',
        conduta: 'Monitorar INR ao iniciar e durante tratamento',
      },
      {
        medicamento: 'Contraceptivos orais (etinilestradiol)',
        gravidade: 'moderada',
        efeito: 'Aumento dos niveis de etinilestradiol (50-60%)',
        conduta: 'Maior risco de eventos tromboembolicos; considerar alternativas',
      },
      {
        medicamento: 'IECA/BRA',
        gravidade: 'moderada',
        efeito: 'Atenuacao do efeito anti-hipertensivo',
        conduta: 'Monitorar PA',
      },
      {
        medicamento: 'Litio',
        gravidade: 'moderada',
        efeito: 'Aumento dos niveis de litio',
        conduta: 'Monitorar litemia',
      },
      {
        medicamento: 'Metotrexato',
        gravidade: 'moderada',
        efeito: 'Pode aumentar niveis de metotrexato',
        conduta: 'Monitorar toxicidade do MTX',
      },
    ],
    ajusteDoseRenal: [
      { tfg: '30-60', ajuste: 'Sem ajuste; monitorar funcao renal' },
      { tfg: '<30', ajuste: 'Evitar uso' },
    ],
    gestacao: 'X',
    amamentacao: {
      compativel: false,
      observacao: 'Contraindicado. Evitar.',
    },
    monitorizacao: [
      'Pressao arterial (verificar antes e regularmente)',
      'Funcao renal',
      'Funcao hepatica',
      'Sinais de sangramento GI',
      'Peso e edema',
    ],
    orientacoesPaciente: [
      'Verificar pressao arterial regularmente',
      'Usar menor dose pelo menor tempo',
      'Relatar dor toracica, dispneia, fraqueza subita',
      'Nao usar em doenca cardiaca conhecida',
      'Evitar se hipertensao nao controlada',
    ],
    consideracoesEspeciais: {
      idosos: 'Maior risco de eventos adversos. Evitar em cardiopatas.',
      hepatopatas: 'Leve: sem ajuste. Moderada: max 60mg/dia. Grave: evitar.',
      pediatrico: 'Nao recomendado em <16 anos',
    },
    doencasRelacionadas: ['osteoartrite', 'artrite-reumatoide', 'espondilite-anquilosante', 'gota'],
    calculadoras: ['ckdepi'],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['etoricoxibe', 'Arcoxia', 'COX-2', 'coxibe', 'anti-inflamatorio', 'gota'],
  },

  {
    id: 'parecoxibe',
    nomeGenerico: 'Parecoxibe sodico',
    nomesComerciais: ['Dynastat', 'Bextra IV'],
    atcCode: 'M01AH04',
    rxNormCui: '283521',
    drugBankId: 'DB00166',
    snomedCT: '395765007',
    casNumber: '198470-85-8',
    classeTerapeutica: 'anti_inflamatorio',
    subclasse: 'seletivo_cox2',
    rename: false,
    apresentacoes: [
      { forma: 'po_injetavel', concentracao: '40mg (IV/IM)', disponivelSUS: false },
    ],
    indicacoes: [
      'Dor pos-operatoria de curta duracao',
      'Analgesia multimodal perioperatoria',
      'Quando via oral nao e possivel',
    ],
    mecanismoAcao: 'Pro-droga do valdecoxibe, um inibidor seletivo de COX-2. Apos administracao parenteral, e rapidamente convertido em valdecoxibe por esterases plasmaticas e hepaticas. Fornece analgesia potente via inibicao de COX-2 no pos-operatorio, quando a via oral nao esta disponivel. Inicio de acao em 7-13 minutos (IV).',
    posologias: [
      {
        indicacao: 'Dor pos-operatoria',
        adultos: {
          dose: '40mg IV ou IM inicial, seguido de 20-40mg a cada 6-12h',
          frequencia: 'A cada 6-12 horas',
          doseMaxima: '80mg/dia',
          observacoes: 'Uso por maximo 3 dias. Converter para via oral assim que possivel.',
        },
        idosos: {
          dose: '20mg inicial, depois 20mg cada 6-12h',
          observacoes: 'Pacientes <50kg ou >65 anos: dose maxima 40mg/dia',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade a parecoxibe, valdecoxibe ou sulfonamidas',
      'Historia de asma, urticaria ou reacoes alergicas a AINEs',
      'Ulcera peptica ativa ou sangramento GI',
      'Doenca inflamatoria intestinal grave',
      'Insuficiencia cardiaca grave (NYHA III-IV)',
      'Doenca arterial coronariana ou cerebrovascular estabelecida',
      'Insuficiencia hepatica grave',
      'Cirurgia de revascularizacao coronariana (CABG)',
      'Gestacao (3o trimestre) e lactacao',
    ],
    precaucoes: [
      'Risco cardiovascular - limitar duracao do tratamento',
      'Risco de sangramento - especialmente em cirurgias com alto risco hemorragico',
      'Insuficiencia renal - monitorar funcao',
      'Reacoes cutaneas graves descritas com valdecoxibe',
      'Idosos e pacientes debilitados - doses menores',
    ],
    efeitosAdversos: {
      comuns: [
        'Nausea',
        'Vomitos',
        'Dor abdominal',
        'Prurido',
        'Edema periferico',
        'Oliguria pos-operatoria',
      ],
      graves: [
        'Eventos cardiovasculares (IAM, AVC)',
        'Sangramento GI',
        'Insuficiencia renal aguda',
        'Reacoes cutaneas graves (Stevens-Johnson, NET)',
        'Broncoespasmo em asmaticos sensiveis',
        'Anafilaxia',
      ],
    },
    interacoes: [
      {
        medicamento: 'Anticoagulantes (heparina, varfarina)',
        gravidade: 'grave',
        efeito: 'Aumento do risco de sangramento',
        conduta: 'Monitorar coagulacao rigorosamente',
      },
      {
        medicamento: 'Fluconazol',
        gravidade: 'moderada',
        efeito: 'Aumento dos niveis de valdecoxibe (dobro)',
        conduta: 'Reduzir dose de parecoxibe pela metade',
      },
      {
        medicamento: 'IECA/BRA',
        gravidade: 'moderada',
        efeito: 'Reducao do efeito anti-hipertensivo; risco de IRA',
        conduta: 'Monitorar PA e funcao renal',
      },
      {
        medicamento: 'Opioide (analgesia multimodal)',
        gravidade: 'leve',
        efeito: 'Efeito analgesico sinergico - permite reducao da dose de opioide',
        conduta: 'Uso terapeutico - reduzir necessidade de opioides em 30-40%',
      },
    ],
    ajusteDoseRenal: [
      { tfg: '>30', ajuste: 'Usar com cautela' },
      { tfg: '<30', ajuste: 'Nao recomendado' },
    ],
    gestacao: 'C',
    amamentacao: {
      compativel: false,
      observacao: 'Contraindicado. Valdecoxibe excretado no leite.',
    },
    monitorizacao: [
      'Funcao renal',
      'Debito urinario',
      'Sinais de sangramento',
      'Pressao arterial',
      'Reacoes cutaneas',
    ],
    orientacoesPaciente: [
      'Uso exclusivamente hospitalar',
      'Relatar reacoes cutaneas ou sintomas alergicos imediatamente',
      'Sera convertido para analgesia oral assim que possivel',
    ],
    consideracoesEspeciais: {
      idosos: 'Dose maxima 40mg/dia. Iniciar com 20mg.',
      hepatopatas: 'Leve: sem ajuste. Moderada: iniciar com 20mg, max 40mg/dia. Grave: evitar.',
      pediatrico: 'Nao aprovado para <18 anos',
    },
    doencasRelacionadas: ['dor-pos-operatoria'],
    calculadoras: ['ckdepi'],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['parecoxibe', 'Dynastat', 'COX-2', 'coxibe', 'pos-operatorio', 'IV', 'analgesia-multimodal'],
  },

  // =============================================================================
  // ANALGESICOS TOPICOS
  // =============================================================================
  {
    id: 'lidocaina-adesivo',
    nomeGenerico: 'Lidocaina (adesivo topico)',
    nomesComerciais: ['Lidoderm', 'Xylocaine Patch'],
    atcCode: 'N01BB02',
    rxNormCui: '1013890',
    drugBankId: 'DB00281',
    snomedCT: '387480006',
    casNumber: '137-58-6',
    classeTerapeutica: 'analgesico',
    subclasse: 'anestesico_local',
    rename: false,
    apresentacoes: [
      { forma: 'adesivo', concentracao: '5% (700mg por adesivo 10x14cm)', disponivelSUS: false },
      { forma: 'adesivo', concentracao: '5% (140mg por adesivo menor)', disponivelSUS: false },
    ],
    indicacoes: [
      'Neuralgia pos-herpetica',
      'Dor neuropatica localizada',
      'Dor musculoesqueletica localizada (off-label)',
      'Alodinia mecanica',
    ],
    mecanismoAcao: 'Anestesico local do grupo amida que bloqueia canais de sodio voltagem-dependentes nos nervos perifericos. O adesivo proporciona liberacao continua de lidocaina atraves da pele, produzindo analgesia local sem anestesia completa. Absoricao sistemica minima (<5%) quando usado corretamente, minimizando efeitos centrais e toxicidade.',
    posologias: [
      {
        indicacao: 'Neuralgia pos-herpetica',
        adultos: {
          dose: 'Ate 3 adesivos simultaneamente',
          frequencia: '12 horas ligado / 12 horas desligado',
          doseMaxima: '3 adesivos de 5%',
          observacoes: 'Aplicar sobre pele integra na area dolorosa. Evitar membranas mucosas.',
        },
      },
      {
        indicacao: 'Dor neuropatica localizada',
        adultos: {
          dose: '1-3 adesivos sobre area dolorosa',
          frequencia: 'Maximo 12h/dia',
          observacoes: 'Pode cortar o adesivo para ajustar a area',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade a lidocaina ou anestesicos locais tipo amida',
      'Aplicacao em pele nao integra, lesoes ativas de herpes, inflamacao',
    ],
    precaucoes: [
      'Insuficiencia hepatica grave - metabolismo reduzido',
      'Uso de antiarritmicos Classe I (tocainida, mexiletina) - toxicidade aditiva',
      'Nao aplicar sobre feridas abertas',
      'Evitar fontes de calor externa sobre o adesivo - aumenta absorcao',
      'Area de aplicacao extensa pode aumentar absorcao sistemica',
    ],
    efeitosAdversos: {
      comuns: [
        'Reacoes no local (eritema, edema, irritacao)',
        'Prurido',
        'Rash cutaneo',
      ],
      graves: [
        'Reacoes alergicas sistemicas (raro)',
        'Toxicidade por lidocaina se absorcao excessiva (tonturas, sonolencia, arritmias)',
        'Dermatite de contato',
      ],
    },
    interacoes: [
      {
        medicamento: 'Antiarritmicos Classe I (tocainida, mexiletina)',
        gravidade: 'moderada',
        efeito: 'Toxicidade aditiva por anestesicos locais',
        mecanismo: 'Todos bloqueiam canais de sodio',
        conduta: 'Usar com cautela; monitorar sinais de toxicidade',
      },
      {
        medicamento: 'Outros produtos com lidocaina',
        gravidade: 'moderada',
        efeito: 'Risco de toxicidade cumulativa',
        conduta: 'Considerar exposicao total a lidocaina de todas as fontes',
      },
    ],
    gestacao: 'B',
    amamentacao: {
      compativel: true,
      observacao: 'Absoricao sistemica minima. Provavelmente compativel.',
    },
    monitorizacao: [
      'Reacoes cutaneas locais',
      'Sinais de toxicidade sistemica (tonturas, sonolencia)',
      'Eficacia analgesica',
    ],
    orientacoesPaciente: [
      'Aplicar sobre pele limpa, seca e integra',
      'Manter por no maximo 12 horas, remover por 12 horas',
      'Nao aplicar fontes de calor sobre o adesivo',
      'Pode cortar o adesivo para ajustar ao tamanho da area',
      'Descartar adesivo usado em local seguro (ainda contem lidocaina)',
    ],
    consideracoesEspeciais: {
      idosos: 'Usar com cautela. Maior sensibilidade a anestesicos locais.',
      hepatopatas: 'Grave: evitar ou reduzir numero de adesivos',
      pediatrico: 'Seguranca nao estabelecida em <18 anos para esta indicacao',
    },
    doencasRelacionadas: ['neuralgia-pos-herpetica', 'dor-neuropatica', 'herpes-zoster'],
    calculadoras: [],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['lidocaina', 'Lidoderm', 'adesivo', 'topico', 'neuralgia', 'dor-neuropatica'],
  },

  {
    id: 'capsaicina-adesivo',
    nomeGenerico: 'Capsaicina (adesivo alta concentracao)',
    nomesComerciais: ['Qutenza'],
    atcCode: 'N01BX04',
    rxNormCui: '998211',
    drugBankId: 'DB06774',
    snomedCT: '395887003',
    casNumber: '404-86-4',
    classeTerapeutica: 'analgesico',
    subclasse: 'topico',
    rename: false,
    apresentacoes: [
      { forma: 'adesivo', concentracao: '8% (179mg capsaicina por adesivo 14x20cm)', disponivelSUS: false },
    ],
    indicacoes: [
      'Neuralgia pos-herpetica',
      'Neuropatia periferica diabetica dolorosa (pes)',
      'Neuropatia associada ao HIV',
      'Dor neuropatica periferica nao-diabetica',
    ],
    mecanismoAcao: 'Agonista altamente seletivo do receptor vanilloide TRPV1 (receptor de potencial transitorio vaniloide tipo 1). A exposicao a alta concentracao de capsaicina causa dessensibilizacao prolongada dos nociceptores cutaneos expressando TRPV1. Ocorre "desfuncionalizacao" reversivel das fibras nervosas da dor na pele tratada, proporcionando alivio prolongado (ate 3 meses) apos aplicacao unica.',
    posologias: [
      {
        indicacao: 'Neuralgia pos-herpetica (exceto face)',
        adultos: {
          dose: 'Ate 4 adesivos por sessao',
          frequencia: 'Aplicacao de 60 minutos a cada 3 meses',
          observacoes: 'Aplicacao exclusivamente por profissional de saude treinado. Pre-tratamento com anestesico topico.',
        },
      },
      {
        indicacao: 'Neuropatia diabetica dos pes',
        adultos: {
          dose: 'Ate 2 adesivos (um por pe)',
          frequencia: 'Aplicacao de 30 minutos a cada 3 meses',
          observacoes: 'Apenas nos pes. Nao ultrapassar 30 minutos.',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade a capsaicina',
      'Aplicacao na face (risco de mucosas)',
      'Pele nao integra ou lesoes ativas',
    ],
    precaucoes: [
      'Aplicacao exclusivamente por profissional treinado',
      'Dor intensa durante e imediatamente apos aplicacao (usar analgesia)',
      'Hipertensao transitoria durante procedimento - monitorar PA',
      'Protecao do aplicador - usar luvas de nitrila',
      'Nao tocar olhos, boca ou genitais durante procedimento',
      'Diabeticos - inspecionar pes cuidadosamente antes da aplicacao',
    ],
    efeitosAdversos: {
      comuns: [
        'Dor no local (aplicacao) - praticamente universal',
        'Eritema (63%)',
        'Prurido',
        'Papulas',
        'Vesiculas',
        'Edema',
        'Ressecamento cutaneo',
      ],
      graves: [
        'Hipertensao transitoria',
        'Dor severa requerendo analgesicos opioides',
        'Queimaduras se tempo excedido',
        'Reducao na percepcao termica (transitoria)',
      ],
    },
    interacoes: [
      {
        medicamento: 'Nao ha interacoes medicamentosas sistemicas significativas',
        gravidade: 'leve',
        efeito: 'Absorcao sistemica muito baixa',
        conduta: 'Interacao clinicamente irrelevante',
      },
    ],
    gestacao: 'B',
    amamentacao: {
      compativel: true,
      observacao: 'Absorcao sistemica minima. Provavelmente compativel.',
    },
    monitorizacao: [
      'Pressao arterial durante aplicacao',
      'Nivel de dor durante e apos',
      'Reacoes cutaneas',
      'Eficacia analgesica (escala de dor)',
    ],
    orientacoesPaciente: [
      'Procedimento realizado em clinica/hospital por profissional treinado',
      'Esperar dor e sensacao de queimacao durante a aplicacao',
      'Pode usar analgesia oral antes do procedimento',
      'Evitar banhos quentes nas primeiras 24h',
      'Efeito maximo em 1-2 semanas; duracao ate 3 meses',
    ],
    consideracoesEspeciais: {
      idosos: 'Sem restricoes especificas. Monitorar PA.',
      hepatopatas: 'Sem ajuste - absorcao sistemica minima',
      pediatrico: 'Nao aprovado para <18 anos',
    },
    doencasRelacionadas: ['neuralgia-pos-herpetica', 'neuropatia-diabetica', 'neuropatia-hiv'],
    calculadoras: [],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['capsaicina', 'Qutenza', 'adesivo', 'topico', 'TRPV1', 'dor-neuropatica', '8%'],
  },

  // =============================================================================
  // ANALGESICOS ESPECIAIS (USO RESTRITO)
  // =============================================================================
  {
    id: 'ziconotida',
    nomeGenerico: 'Ziconotida',
    nomesComerciais: ['Prialt'],
    atcCode: 'N02BG08',
    rxNormCui: '404644',
    drugBankId: 'DB06286',
    snomedCT: '421889005',
    casNumber: '107452-89-1',
    classeTerapeutica: 'analgesico',
    subclasse: 'outros',
    rename: false,
    apresentacoes: [
      { forma: 'solucao_inalacao', concentracao: '25mcg/mL (frasco 20mL) - INTRATECAL', disponivelSUS: false },
      { forma: 'solucao_inalacao', concentracao: '100mcg/mL (frasco 1, 2 ou 5mL) - INTRATECAL', disponivelSUS: false },
    ],
    indicacoes: [
      'Dor cronica grave em pacientes que requerem terapia intratecal',
      'Dor refrataria a tratamentos convencionais incluindo opioides intratecais',
      'Dor oncologica grave',
      'Dor nao-oncologica cronica refrataria',
      'AIDS ou dor relacionada ao cancer',
    ],
    mecanismoAcao: 'Peptideo sintetico (omega-conotoxina) derivado do veneno do caramujo marinho Conus magus. Bloqueia seletivamente canais de calcio tipo N (Cav2.2) voltagem-dependentes nos terminais aferentes primarios do corno dorsal da medula. Estes canais sao essenciais para liberacao de neurotransmissores excitatarios na transmissao nociceptiva. Mecanismo nao-opioide sem tolerancia, dependencia ou depressao respiratoria.',
    posologias: [
      {
        indicacao: 'Dor cronica grave (adultos)',
        adultos: {
          dose: 'Inicio: <=2,4mcg/dia; Titulacao: aumentar <=2,4mcg/dia nao mais que 2-3x/semana',
          frequencia: 'Infusao intratecal continua via bomba implantavel',
          doseMaxima: '19,2mcg/dia (21,6mcg/dia em bula europeia)',
          observacoes: 'Titulacao extremamente lenta necessaria. Resposta pode levar semanas. Iniciar com dose mais baixa possivel.',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade a ziconotida',
      'Historia de psicose',
      'Infeccao no local do cateter ou sistemica nao tratada',
      'Obstrucao do fluxo liquorico',
      'Uso concomitante de quimioterapia intratecal',
    ],
    precaucoes: [
      'Disturbios psiquiatricos - pode induzir ou agravar (psicose, alucinacoes, depressao, ideacao suicida)',
      'Comprometimento cognitivo - muito comum',
      'Meningite - risco relacionado ao cateter',
      'CPK elevada - monitorar (pode indicar rabdomiolise)',
      'Nao descontinuar abruptamente - titular para baixo',
      'Treinamento especial necessario para profissionais',
    ],
    efeitosAdversos: {
      comuns: [
        'Tontura (47%)',
        'Nausea (30%)',
        'Confusao (25%)',
        'Cefaleia (15%)',
        'Sonolencia (17%)',
        'Nistagmo (8%)',
        'Disturbios da marcha (14%)',
        'Deficit de memoria (7%)',
        'Visao turva',
        'Vomitos',
        'Astenia',
      ],
      graves: [
        'Psicose e alucinacoes',
        'Ideacao suicida e suicidio',
        'Depressao grave',
        'Comprometimento cognitivo grave',
        'Meningite (relacionada ao cateter)',
        'Rabdomiolise (raro)',
        'Convulsoes',
      ],
    },
    interacoes: [
      {
        medicamento: 'Opioides intratecais (morfina IT)',
        gravidade: 'moderada',
        efeito: 'Pode ser usada em combinacao com reducao da dose de opioide; monitorar sedacao',
        conduta: 'Combinacao pode ser sinergica; reduzir dose de ambos',
      },
      {
        medicamento: 'Depressores do SNC (benzodiazepinicos, alcool)',
        gravidade: 'moderada',
        efeito: 'Sedacao e confusao aumentadas',
        conduta: 'Usar com cautela; monitorar estado mental',
      },
      {
        medicamento: 'Antipsicoticos',
        gravidade: 'moderada',
        efeito: 'Podem mascarar sintomas de psicose induzida por ziconotida',
        conduta: 'Monitorar rigorosamente sintomas psiquiatricos',
      },
    ],
    gestacao: 'C',
    amamentacao: {
      compativel: false,
      observacao: 'Sem dados. Evitar.',
    },
    monitorizacao: [
      'Avaliacao psiquiatrica regular (psicose, depressao, suicidio)',
      'CPK serica periodica',
      'Funcao cognitiva',
      'Sinais de meningite',
      'Eficacia analgesica',
      'Funcao do cateter e bomba',
    ],
    orientacoesPaciente: [
      'Tratamento requer bomba intratecal implantavel',
      'Relatar imediatamente mudancas de humor, pensamentos de se machucar',
      'Relatar confusao, dificuldade de concentracao',
      'Relatar febre, rigidez de nuca (sinais de meningite)',
      'Nao dirigir durante tratamento',
      'Visitas regulares para ajuste de bomba e avaliacao',
    ],
    consideracoesEspeciais: {
      idosos: 'Maior sensibilidade a efeitos sobre SNC. Titulacao ainda mais lenta.',
      hepatopatas: 'Sem ajuste necessario',
      pediatrico: 'Seguranca e eficacia nao estabelecidas em <18 anos',
    },
    doencasRelacionadas: ['dor-cronica-refrataria', 'dor-oncologica', 'dor-neuropatica'],
    calculadoras: [],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['ziconotida', 'Prialt', 'intratecal', 'conotoxina', 'canal-calcio', 'dor-refrataria'],
  },

  {
    id: 'cetamina',
    nomeGenerico: 'Cetamina (Ketamina)',
    nomesComerciais: ['Ketalar', 'Ketamin'],
    atcCode: 'N01AX03',
    rxNormCui: '6130',
    drugBankId: 'DB01221',
    snomedCT: '373464007',
    casNumber: '6740-88-1',
    loinc: ['3748-2'],
    classeTerapeutica: 'analgesico',
    subclasse: 'antagonista_nmda',
    rename: true,
    pharmgkb: [
      {
        gene: 'CYP2B6',
        phenotype: 'poor_metabolizer',
        implications: [
          'CYP2B6 e CYP3A4 metabolizam cetamina a norcetamina',
          'Metabolizadores lentos podem ter exposicao aumentada',
        ],
        dosageRecommendations: [
          'Monitorar resposta e efeitos adversos',
          'Pode requerer ajuste de dose em metabolizadores lentos',
        ],
      },
    ],
    apresentacoes: [
      { forma: 'injetavel', concentracao: '50mg/mL (frasco 10mL)', disponivelSUS: true },
      { forma: 'injetavel', concentracao: '10mg/mL (frasco 20mL)', disponivelSUS: false },
    ],
    indicacoes: [
      'Inducao e manutencao de anestesia geral',
      'Sedacao procedural',
      'Analgesia em doses subanestesicas',
      'Dor aguda perioperatoria (adjuvante)',
      'Dor cronica refrataria (infusao IV)',
      'Depressao resistente ao tratamento (off-label e formulacoes especificas)',
      'Status epilepticus refratario',
    ],
    mecanismoAcao: 'Antagonista nao-competitivo do receptor NMDA (N-metil-D-aspartato) do glutamato. Em doses anestesicas, produz estado dissociativo com analgesia profunda, amnesia e catalepsia. Em doses subanestesicas, proporciona analgesia potente e pode prevenir sensibilizacao central e hiperalgesia induzida por opioides. Tambem interage com receptores opioides, monoaminergicos e colinergicos. Acoes antidepressivas rapidas via modulacao glutamatergica.',
    posologias: [
      {
        indicacao: 'Inducao anestesica (IV)',
        adultos: {
          dose: '1-4,5mg/kg IV lento',
          frequencia: 'Dose unica de inducao',
          observacoes: 'Inicio de acao em 30 segundos. Duracao 5-10 minutos.',
        },
        pediatrico: {
          dose: '1-2mg/kg IV',
          frequencia: 'Dose unica de inducao',
          observacoes: 'Criancas geralmente requerem doses proporcionalmente maiores',
        },
      },
      {
        indicacao: 'Inducao anestesica (IM)',
        adultos: {
          dose: '6,5-13mg/kg IM',
          frequencia: 'Dose unica',
          observacoes: 'Inicio em 3-4 minutos. Util quando acesso IV dificil.',
        },
      },
      {
        indicacao: 'Analgesia subanestesica (adjuvante)',
        adultos: {
          dose: '0,1-0,5mg/kg IV em bolus ou 0,1-0,3mg/kg/h infusao',
          frequencia: 'Conforme necessidade',
          observacoes: 'Analgesia opioide-sparing. Reduz hiperalgesia.',
        },
      },
      {
        indicacao: 'Dor cronica (infusao IV)',
        adultos: {
          dose: '0,5mg/kg em 40min ate 0,35mg/kg/h por 4-6h',
          frequencia: 'Sessoes periodicas (semanal a mensal)',
          observacoes: 'Ambiente controlado. Monitoramento continuo.',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade a cetamina',
      'Condicoes onde elevacao da pressao arterial e perigosa (pre-eclampsia, aneurisma, HIC)',
      'Hipertensao intracraniana',
      'Eclampsia',
      'Historia de AVC recente',
      'Porfiria',
    ],
    precaucoes: [
      'Efeitos psicotomimeticos - pesadelos, alucinacoes, delirio na emergencia',
      'Hipertensao e taquicardia - monitorar rigorosamente',
      'Laringoespasmo - mais comum em criancas',
      'Aumento da pressao intraocular',
      'Dependencia e abuso - potencial de uso recreativo',
      'Cistite ulcerativa com uso cronico/abuso',
      'Hepatotoxicidade com uso prolongado',
      'Pre-tratamento com benzodiazepinicos reduz fenomenos de emergencia',
    ],
    efeitosAdversos: {
      comuns: [
        'Fenomenos de emergencia (alucinacoes, pesadelos, delirio) - 12-30%',
        'Nistagmo',
        'Hipertensao',
        'Taquicardia',
        'Nausea e vomitos',
        'Hipersalivacao',
        'Diplopia',
        'Tontura',
      ],
      graves: [
        'Laringoespasmo',
        'Apneia (doses altas rapidas)',
        'Depressao respiratoria (associacao com depressores)',
        'Arritmias',
        'Aumento da PIC',
        'Cistite ulcerativa (uso cronico)',
        'Hepatotoxicidade (uso prolongado)',
        'Dependencia',
      ],
    },
    interacoes: [
      {
        medicamento: 'Benzodiazepinicos (midazolam, diazepam)',
        gravidade: 'moderada',
        efeito: 'Reduzem fenomenos de emergencia; potencializam sedacao',
        mecanismo: 'Efeito aditivo sobre SNC',
        conduta: 'Co-administracao frequentemente util. Ajustar doses.',
      },
      {
        medicamento: 'Opioides',
        gravidade: 'moderada',
        efeito: 'Sinergismo analgesico; reducao de hiperalgesia induzida por opioides',
        conduta: 'Combinacao terapeuticamente util. Monitorar depressao respiratoria.',
      },
      {
        medicamento: 'Agentes simpatomiméticos (epinefrina)',
        gravidade: 'moderada',
        efeito: 'Potencializacao de efeitos cardiovasculares (hipertensao, taquicardia)',
        conduta: 'Monitorar rigorosamente hemodinamica',
      },
      {
        medicamento: 'Tiopental, propofol',
        gravidade: 'leve',
        efeito: 'Antagonismo hemodinamico - cetamina pode compensar hipotensao de outros agentes',
        conduta: 'Usado terapeuticamente em pacientes instáveis',
      },
    ],
    gestacao: 'B',
    amamentacao: {
      compativel: false,
      observacao: 'Evitar. Excretada no leite. Aguardar 12-24h apos uso.',
    },
    monitorizacao: [
      'Pressao arterial e frequencia cardiaca (aumento esperado)',
      'Frequencia respiratoria e saturacao',
      'Nivel de consciencia',
      'Sinais de laringoespasmo',
      'Estado mental na emergencia da anestesia',
    ],
    orientacoesPaciente: [
      'Pode causar sonhos vividos ou alucinacoes na recuperacao',
      'Nao dirigir por 24 horas apos procedimento',
      'Relatar tonturas, confusao ou problemas urinarios',
      'Para dor cronica: aderir ao programa de tratamento supervisionado',
    ],
    consideracoesEspeciais: {
      idosos: 'Doses menores recomendadas. Fenomenos de emergencia podem ser menos intensos.',
      hepatopatas: 'Usar com cautela em insuficiencia grave.',
      pediatrico: 'Geralmente bem tolerada. Doses mg/kg podem ser proporcionalmente maiores.',
    },
    doencasRelacionadas: ['anestesia', 'dor-aguda', 'dor-cronica', 'depressao-resistente'],
    calculadoras: [],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['cetamina', 'ketamina', 'NMDA', 'anestesico', 'dissociativo', 'Ketalar', 'dor-cronica'],
  },

  {
    id: 'nefopam',
    nomeGenerico: 'Nefopam',
    nomesComerciais: ['Acupan'],
    atcCode: 'N02BG06',
    rxNormCui: '28879',
    drugBankId: 'DB04910',
    snomedCT: '372908005',
    casNumber: '13669-70-0',
    classeTerapeutica: 'analgesico',
    subclasse: 'nao_opioide',
    rename: false,
    apresentacoes: [
      { forma: 'injetavel', concentracao: '20mg/2mL (IM/IV)', disponivelSUS: false },
      { forma: 'comprimido', concentracao: '30mg (disponivel em alguns paises)', disponivelSUS: false },
    ],
    indicacoes: [
      'Dor aguda moderada a grave',
      'Dor pos-operatoria',
      'Analgesia multimodal (adjuvante a opioides)',
      'Dor traumatica',
      'Colica renal (alguns protocolos)',
      'Dor quando opioides sao indesejados',
    ],
    mecanismoAcao: 'Analgesico central nao-opioide de mecanismo unico. Inibe a recaptacao de serotonina, noradrenalina e dopamina (triplice inibidor). Tambem modula canais de sodio voltagem-dependentes e pode ter acoes anticolinergicas leves. Nao atua em receptores opioides, nao causa depressao respiratoria, constipacao ou dependencia fisica. Potencia analgesica comparavel a doses moderadas de opioides com perfil de efeitos adversos distinto.',
    posologias: [
      {
        indicacao: 'Dor aguda (adultos)',
        adultos: {
          dose: '20mg IM ou IV lento (>15 minutos)',
          frequencia: 'A cada 6 horas',
          doseMaxima: '120mg/dia',
          observacoes: 'Via IV deve ser lenta para minimizar taquicardia. Pode ser diluido em SF ou SG.',
        },
      },
      {
        indicacao: 'Dor pos-operatoria (infusao)',
        adultos: {
          dose: '60-120mg/24h em infusao continua',
          frequencia: 'Infusao continua',
          observacoes: 'Parte de esquema de analgesia multimodal',
        },
      },
    ],
    contraindicacoes: [
      'Hipersensibilidade ao nefopam',
      'Convulsoes ou historia de epilepsia',
      'Risco de retencao urinaria (hipertrofia prostatica grave)',
      'Glaucoma de angulo fechado',
      'IAM recente ou insuficiencia cardiaca grave',
    ],
    precaucoes: [
      'Taquicardia - efeito anticolinergico; evitar em arritmias',
      'Sudorese intensa - efeito comum',
      'Retencao urinaria - especialmente em idosos',
      'Confusao mental - mais comum em idosos',
      'Nausea e vomitos',
      'Uso concomitante com IMAO - risco de sindrome serotoninergica',
      'Evitar em pacientes com risco de convulsoes',
    ],
    efeitosAdversos: {
      comuns: [
        'Taquicardia (15%)',
        'Sudorese (10%)',
        'Nausea',
        'Tontura',
        'Sonolencia',
        'Boca seca',
        'Nervosismo',
      ],
      graves: [
        'Convulsoes (raro, principalmente em predispostos)',
        'Retencao urinaria',
        'Confusao e agitacao',
        'Alucinacoes (raro)',
        'Sindrome serotoninergica (com IMAO)',
        'Abuso (raro, mas descrito)',
      ],
    },
    interacoes: [
      {
        medicamento: 'IMAO',
        gravidade: 'contraindicada',
        efeito: 'Risco de sindrome serotoninergica',
        mecanismo: 'Nefopam inibe recaptacao de monoaminas',
        conduta: 'Evitar. Intervalo minimo de 14 dias.',
      },
      {
        medicamento: 'Anticolinergicos (atropina, escopolamina)',
        gravidade: 'moderada',
        efeito: 'Potencializacao de efeitos anticolinergicos',
        conduta: 'Monitorar retencao urinaria, confusao, taquicardia',
      },
      {
        medicamento: 'Opioides',
        gravidade: 'leve',
        efeito: 'Sinergismo analgesico - permite reducao de dose de opioide',
        conduta: 'Combinacao util em analgesia multimodal',
      },
      {
        medicamento: 'Antidepressivos triciclicos, ISRS',
        gravidade: 'moderada',
        efeito: 'Risco teorico de sindrome serotoninergica',
        conduta: 'Usar com cautela; monitorar',
      },
    ],
    ajusteDoseRenal: [
      { tfg: '>30', ajuste: 'Usar com cautela' },
      { tfg: '<30', ajuste: 'Reducao de dose ou evitar - eliminacao renal de metabolitos' },
    ],
    gestacao: 'C',
    amamentacao: {
      compativel: false,
      observacao: 'Dados insuficientes. Evitar.',
    },
    monitorizacao: [
      'Frequencia cardiaca (taquicardia comum)',
      'Debito urinario (risco de retencao)',
      'Estado mental (especialmente em idosos)',
      'Eficacia analgesica',
    ],
    orientacoesPaciente: [
      'Relatar palpitacoes ou batimentos acelerados',
      'Relatar dificuldade para urinar',
      'Sudorese e e efeito comum e esperado',
      'Nao dirigir se apresentar tontura',
      'Nao usar com medicamentos para depressao sem orientacao',
    ],
    consideracoesEspeciais: {
      idosos: 'Maior risco de confusao e retencao urinaria. Doses menores.',
      hepatopatas: 'Usar com cautela em insuficiencia moderada a grave.',
      pediatrico: 'Nao recomendado em <15 anos',
    },
    doencasRelacionadas: ['dor-aguda', 'dor-pos-operatoria', 'colica-renal'],
    calculadoras: [],
    citations: [],
    lastUpdate: '2024-12',
    tags: ['nefopam', 'Acupan', 'analgesico-central', 'nao-opioide', 'multimodal'],
  },
];
